# Generated by Django 3.2.6 on 2021-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nails',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
