# Generated by Django 3.2.6 on 2021-08-19 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nails', '0002_alter_nails_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nails',
            new_name='Feedback',
        ),
    ]
